// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAboutInfo() {
  return window['go']['main']['App']['GetAboutInfo']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetQRCode() {
  return window['go']['main']['App']['GetQRCode']();
}

export function OpenInBrowser() {
  return window['go']['main']['App']['OpenInBrowser']();
}

export function OpenSharedFolder() {
  return window['go']['main']['App']['OpenSharedFolder']();
}

export function RegenerateSessionPIN() {
  return window['go']['main']['App']['RegenerateSessionPIN']();
}

export function RegenerateUploadPIN() {
  return window['go']['main']['App']['RegenerateUploadPIN']();
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SetPort(arg1) {
  return window['go']['main']['App']['SetPort'](arg1);
}

export function SetUploadEnabled(arg1) {
  return window['go']['main']['App']['SetUploadEnabled'](arg1);
}

export function ShowError(arg1, arg2) {
  return window['go']['main']['App']['ShowError'](arg1, arg2);
}

export function ShowInfo(arg1, arg2) {
  return window['go']['main']['App']['ShowInfo'](arg1, arg2);
}

export function StartServer() {
  return window['go']['main']['App']['StartServer']();
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}
