// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAboutInfo():Promise<Record<string, string>>;

export function GetConfig():Promise<Record<string, any>>;

export function GetQRCode():Promise<string>;

export function OpenInBrowser():Promise<void>;

export function OpenSharedFolder():Promise<void>;

export function RegenerateSessionPIN():Promise<string>;

export function RegenerateUploadPIN():Promise<string>;

export function SelectFolder():Promise<string>;

export function SetPort(arg1:string):Promise<void>;

export function SetUploadEnabled(arg1:boolean):Promise<void>;

export function ShowError(arg1:string,arg2:string):Promise<void>;

export function ShowInfo(arg1:string,arg2:string):Promise<void>;

export function StartServer():Promise<string>;

export function StopServer():Promise<void>;
